name: ServerGuard
version: ${project.version}
main: com.jazzkuh.serverguard.ServerGuard
authors: [Jazzkuh]
description: Protect your server against known malicious and dangerous plugins!
commands:
    serverguard: {}
